#!/bin/bash

dir=`pwd`
# echo Linking to files in $dir ...
# 
# echo Updating submodules ...
# git submodule init
# git submodule update
# git submodule foreach git pull origin master

link_file () {
  local src=$1
  local srcFolder=$(dirname $src)
  local relFolder=${srcFolder#$(pwd)}
  local dstFolder=~/$relFolder
  local basename=$(basename $src)
  local dst=$dstFolder/${basename%".symlink"}

  mkdir -p $dstFolder
  rm -rf $dst
  ln -sf $src $dst
}

for f in $(find $(pwd) -name "*.symlink")
do
  link_file $f
done
