#!/bin/bash

link_file () {
  local src=$1
  local srcFolder=$(dirname $src)
  local relFolder=${srcFolder#$(pwd)}
  local dstFolder=~/$relFolder
  local basename=$(basename $src)
  local dst=$dstFolder/${basename%".symlink"}

  mkdir -p $dstFolder
  rm -rf $dst
  ln -sf $src $dst
}

for f in $(find $(pwd) -name "*.symlink")
do
  echo "Linking" $f
  link_file $f
done
